name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run tests
      env:
        clientId: ${{secrets.appSidProd}}
        clientSecret: ${{secrets.appKeyProd}}
        apiBaseUrl: "https://api.aspose.cloud"
      run: |
        sed -i "s|replaceClientSecret|$clientSecret|g" tests/phpunit.xml
        sed -i "s|replaceClientId|$clientId|g" tests/phpunit.xml
        sed -i "s|replaceApiBaseUrl|$apiBaseUrl|g" tests/phpunit.xml
        sed -i "s|replaceBootstrap|$PWD/vendor/autoload.php|g" tests/phpunit.xml
        vendor/phpunit/phpunit/phpunit --configuration tests/phpunit.xml --testdox tests
